default:
  - test:
    - notebooks_execution:
        pythonContainerRun:
          pythonVersion: '3.11'
          installDependencies: true
          # Note: the 'poetry run' prefix is automatically added to each command
          commands: |-
            python -m ipykernel install --user --name=notebooks-nwp-env --display-name "Python (notebooks-nwp-env)" &&
            python check_notebooks.py
