[tool.poetry]
name = "opendata-nwp-demos"
version = "0.1.0"
description = "Notebook examples using model data for the Open Government Data initiative"
authors = ["MeteoSwiss"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = ">=3.11,<3.14"
earthkit-plots = "0.3.3"
ipykernel = "^6.29.5"
rasterio = "^1.4.3"
earthkit-geo = "^0.5.2"
earthkit-transforms = "^1.0.0"
geopandas = "^1.1.4"
earthkit-data-meteoswiss-opendata = "0.2.0"
earthkit-meteo = "^1.0.0"
eccodes-cosmo-resources-python = "^2.47.0.1"
meteodata-lab = "^0.8.0"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
nbconvert = "^7.17.0"
nbformat = "^5.10.4"


[tool.poetry.group.nbformat.dependencies]
nbformat = "^5.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
