[tool.poetry]
name = "opendata-nwp-demos"
version = "0.1.0"
description = ""
authors = ["ninaburg <nina.burg@hotmail.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "~3.11"
meteodata-lab = { url = "https://github.com/MeteoSwiss/meteodata-lab/archive/b3cfc6144705725fbe81b2f29fb4cfd4f5d71d3b.zip" }
earthkit-plots = "^0.2.8"
ipykernel = "^6.29.5"
rasterio = "^1.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
